# Generated by Django 5.2.12 on 2026-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes sur la configuration de ce test', null=True)),
                ('report_file_path', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
